#!/usr/bin/bash
# Pretend a PDF was scanned - requires convert
exec convert -density 150 "$1" -colorspace gray -linear-stretch 3.5%x10% -blur 0x0.5 -attenuate 0.25 +noise Gaussian -rotate 0.5 "${1%.*}fake.${1##*.}"
