#!/bin/sh
# Start Firefox with a temporary profile

set -eu

PROFILEDIR=$(mktemp -p /tmp -d tmp-ff-profile.XXXXXX.d)
trap 'rm -rf "$PROFILEDIR"' EXIT HUP INT QUIT TERM
firefox -profile "$PROFILEDIR" -no-remote -new-instance -private-window
