#!/bin/bash

whitelist_repo="dotfiles"
protected_branch="master"

origin_repo_name=$(basename -s .git "$(git config --get remote.origin.url)")
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$origin_repo_name" != "$whitelist_repo" ] && [ -z ${GIT_ALLOW_MASTER+x} ] && [ "$protected_branch" = "$current_branch" ]; then
    read -p "You're about to push master, is that what you intended? [y|n] " -n 1 -r < /dev/tty
    echo
    if echo "$REPLY" | grep -E '^[Yy]$' > /dev/null
    then
        exit 0 # push will execute
    fi
    exit 1 # push will not execute
else
    exit 0 # push will execute
fi
